name    = "SafeREPL"
uuid    = "5e6a0ad9-8e90-40fa-86b1-deb43b8cfda7"
authors = ["Rafael Fourquet <fourquet.rafael@gmail.com>"]
version = "0.1.0"

[deps]
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[extras]
BitIntegers   = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
SaferIntegers = "88634af6-177f-5301-88b8-7819386cfa38"
Test          = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["BitIntegers", "SaferIntegers", "Test"]

[compat]
julia = "1.5"
